### ISSUE TITLE
Pip install fails for many libs

### ISSUE THREAD

**Issue by KaviyaSubramanian706** [AndreaCodegoni/Tiny_model_4_CD#10]
When I tried to install requirements through conda..many libraries were not present in any of conda channels..so I tried installing in pip
Even then many libs were mismatched
 Python -3.8.10
`ERROR: Could not find a version that satisfies the requirement antlr-python-runtime==4.9.3 (from versions: none)
ERROR: No matching distribution found for antlr-python-runtime==4.9.3

ERROR: Could not find a version that satisfies the requirement blas==1.0 (from versions: none)
ERROR: No matching distribution found for blas==1.0

ERROR: Could not find a version that satisfies the requirement bzip2==1.0.8 (from versions: none)
ERROR: No matching distribution found for bzip2==1.0.8

`
Am I missing any other specifications,or are these versions  or library names to be changed?

**Comment by AndreaCodegoni** [comment]
Hello Kaviya,

You are right, the requirements file is outdated. It was my bad since I had exported the requirements from an anaconda env without carefully checking if this were the minimal requirements to run this project. I'm very sorry.
I think that you only need to install python 3.8 with numpy, torch, torchvision and albumentations and the dependencies that these packages requires.
I kindly ask you if you can open a pr with an updated requirements if you are able to succesfully reproduce the results. 
Thank you in advance.

**Comment by KaviyaSubramanian706** [comment]
Hi..I raised  a pull request for those requirements,
Next inorder to infer the labels predicted I added this code
`
           bin_genmask = (generated_mask > 0.5).numpy()
            bin_genmask = bin_genmask.astype(np.uint8)
            draw_genmask = bin_genmask.reshape(256,256)
            draw_genmask = draw_genmask * 255
            print("DRAW GENMASK : ",draw_genmask)
            print("SHAPE ",draw_genmask.shape)
            img = Image.fromarray(draw_genmask)
            print("img name ",img_name[0])
            img.save("predict/"+str(img_name[0]))
            mask = mask.numpy()
            mask = mask.astype(np.uint8)
            ref_mask = mask.reshape(256,256)
            ref_mask= ref_mask*255
            ref_img = Image.fromarray(ref_mask)
            draw_img = get_concat_h(img,ref_img)

`
This produces image which doesnt look anything like ref labels
But the accuracy is at 95% for WHU-CD dataset
