### ISSUE TITLE
Request for WHU-CD dataset Baiduyun link

### ISSUE THREAD

**Issue by songfish** [AndreaCodegoni/Tiny_model_4_CD#8]
Hi there,

I'm currently working on a research project that requires the WHU-CD dataset. I noticed that a Dropbox link is provided for this dataset, and I was wondering if you have any other links available, such as a Baiduyun link?

Unfortunately, I am located in a region where Dropbox is not accessible, and I am unable to download the dataset. It would be greatly appreciated if you could provide a Baiduyun link or any alternative means of accessing the dataset.

Thank you for your time.

**Comment by AndreaCodegoni** [comment]
HI,

I am very sorry about this problem.
Unfortunately Baiduyun is not accessible for me.
Can't access the original dataset download link? Then you could process the dataset using the code you find in the ChangeFormer repository (https://github.com/wgcban/ChangeFormer/tree/main/data_preparation).

Let me know if you can or if there are other alternatives you could consider so that I can send you the dataset.
